# Path                                                 Mode UID  GID  Age Argument
w /sys/devices/system/cpu/intel_pstate/no_turbo        -    -    -    -   1
w /sys/devices/system/cpu/intel_pstate/max_perf_pct    -    -    -    -   39
w /sys/devices/system/cpu/intel_pstate/min_perf_pct    -    -    -    -   15
