[ids]
*

[main]
capslock = overload(control, esc)
esc = capslock
rightalt = layer(media)
f10 = toggle(dvorak)
f8 = toggle(colemak)

[media]
f2 = volumedown
f3 = volumeup
f4 = mute
f6 = brightnessdown
f7 = brightnessup

# Adding ':main' makes sure Right Alt stays a media trigger
[dvorak:main]
include layouts/dvorak

[colemak:main]
include layouts/colemak
