[ids]
*

[main]
capslock = overload(control, esc)
esc = capslock

# F10 toggles Dvorak, F8 toggles Colemak
f10 = toggle(dvorak)
f8 = toggle(colemak)

[dvorak]
include layouts/dvorak
capslock = overload(control, esc)
# Toggle back to main
f10 = toggle(dvorak)

[colemak]
include layouts/colemak
capslock = overload(control, esc)
# Toggle back to main
f8 = toggle(colemak)
