[ids]
*

[main]
capslock = overload(control, esc)
esc = capslock

# Multimedia Layer Trigger
rightalt = layer(media)

# F10 toggles Dvorak, F8 toggles Colemak
f10 = toggle(dvorak)
f8 = toggle(colemak)

[media]
# TVS Gold Multimedia Mappings
f2 = volumedown
f3 = volumeup

f4 = mute

[dvorak]
include layouts/dvorak
capslock = overload(control, esc)
rightalt = layer(media)
f10 = toggle(dvorak)

[colemak]
include layouts/colemak
capslock = overload(control, esc)
rightalt = layer(media)
f8 = toggle(colemak)
