Load smb config files from /etc/samba/smb.conf
NOTE: Service homes is flagged unavailable.
Loaded services file OK.
Weak crypto is allowed by GnuTLS (e.g. NTLM as a compatibility fallback)

Server role: ROLE_STANDALONE

# Global parameters
[global]
	dns proxy = No
	interfaces = lo tailscale0 enp3s0
	log file = /usr/local/samba/var/log.%m
	max log size = 50
	server role = standalone server
	server string = Samba Server
	workgroup = COVEN
	idmap config * : backend = tdb
	hosts allow = 127.0.0.1 192.168.0.0/16 192.168.1.0/16 100.113.55.98 100.111.244.36 100.114.198.27 100.109.117.51 100.72.196.48 100.67.197.38


[homes]
	available = No
	browseable = No
	comment = Home Directories
	read only = No


[printers]
	browseable = No
	comment = All Printers
	path = /usr/spool/samba
	printable = Yes


[WD1TB]
	comment = western digital 2019 1TB used on i59600
	create mask = 0775
	directory mask = 0775
	path = /mnt/WD1TB
	read only = No
	valid users = spiritedcaveman
	hosts allow = 127.0.0.1 192.168.0.0/16
    hosts deny = 0.0.0.0/0

[music]
    path = /mnt/music
    browseable = yes
    read only = yes
    valid users = spiritedcaveman
    create mask = 0775
    directory mask = 0775

