music_directory    "/mnt/music"
# playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/log"
# state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"

auto_update "no"
restore_paused "no"

# CRITICAL: "any" can be flaky on some Arch setups.
# "0.0.0.0" forces it to listen to all IPv4 addresses.
bind_to_address "127.0.0.1"
port "6600"

audio_output {
    type            "pipewire"
    name            "PipeWire Sound Server"
}

audio_output {
    type                    "fifo"
    name                    "my_fifo"
    path                    "/tmp/mpd.fifo"
    format                  "44100:16:2"
}

audio_output {
    type            "httpd"
    name            "Mac Stream"
    encoder         "flac"          # High quality for your FLAC library
    port            "8000"          # Different port for the audio data
    bind_to_address "0.0.0.0"
    format          "44100:16:2"
    always_on       "yes"           # Keeps the stream alive even when paused
    max_clients     "0"             # 0 = no limit
}
