music_directory    "/mnt/music"
# playlist_directory "/home/spiritedcaveman/.config/mpd/playlists"
db_file            "/home/spiritedcaveman/.config/mpd/database"
log_file           "/home/spiritedcaveman/.config/mpd/log"
state_file         "/home/spiritedcaveman/.config/mpd/state"

bind_to_address    "127.0.0.1"
port               "6600"
auto_update        "yes"

audio_output {
    type            "pipewire"
    name            "PipeWire Sound Server"
}

audio_output {
    type            "fifo"
    name            "my_fifo"
    path            "/tmp/mpd.fifo"
    format          "44100:16:2"
}
