# Shell override to launch straight into Endcord
#shell endcord

# Aesthetics & Performance
remember_window_size  no
initial_width        900
initial_height       700
background_opacity   0.95
window_padding_width 10

# Fonts (Ensures emojis render beside your hacking font)
font_family      Iosevka Term
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        15.0

# Disable features you don't need for a single app
enable_audio_bell no
update_check_interval 0

# Completely disable the tab bar visually
tab_bar_style hidden

# Don't show the tab bar even if multiple windows/tabs are open
tab_bar_min_tabs 1

