# === FOOT CONFIG ===

# Foot uses Pt by default.
font=Ubuntu Mono:size=13.5
pad=3x1                             # Matches Alacritty padding

[scrollback]
lines=7000                          # Matches 7k history limit
multiplier=9.0

[cursor]
style=block
blink=yes
blink-rate=300
color=1a1b26 f8f8f2                # Background Text | Cursor Color

[colors]
# Ported from Alacritty colors
background=1a1b26
foreground=c0caf5

# Dracula-ish palette
regular0=282a36  # black
regular1=ff5555  # red
regular2=50fa7b  # green
regular3=f1fa8c  # yellow
regular4=bd93f9  # blue
regular5=ff79c6  # magenta
regular6=8be9fd  # cyan
regular7=f8f8f2  # white

[main]
term=foot                           # Better for Wayland than forcing 'alacritty'
dpi-aware=no                        # Fixes the "massive font" scaling issue

[mouse]
hide-when-typing=yes

[url]
launch=xdg-open ${url}
label-letters=sadfjklewcmpgh
# style=dotted
# protocols=http, https, ftp, ftps, file, mailto, ipfs, ipns

[url-bindings]
# This matches the action mentioned in local man page
toggle-url-visible=Control+Shift+o


[search-bindings]
# Vim-like navigation within the search box
find-prev=Control+r
find-next=Control+s
cursor-left=Control+b
cursor-right=Control+f

[key-bindings]
# Pipe the current scrollback buffer directly into a pager (Vim/less)
# Perfect for when a log is too long to read in the terminal
pipe-scrollback=[sh -c "tempfile=$(mktemp); cat - > $tempfile; foot -e vim $tempfile; rm $tempfile"] Control+Shift+h
